// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
  "aws_appsync_graphqlEndpoint": "https://x7y7olvj6ze4nm3otxb6bhlz5m.appsync-api.us-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "da2-5zbmkrw5kzab3pamhm2jnqk76e",
};

export default awsmobile;